// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hziifsedpyuazvjdxpsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6aWlmc2VkcHl1YXp2amR4cHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Nzc0MDQsImV4cCI6MjA2NzE1MzQwNH0.4r1e9jRHlCEvyE8kdSpDJSJWOWcG9Selw2x3ShQPGH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});